sudo: required
dist: trusty

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq ggcov

before_script:
  - mkdir _build
  - cd _build
  - cmake ..
  - pip install --user pyyaml cpp-coveralls

script:
  - make
  - make test

after_success:
  - ./mongoose_test_io_coverage
  - cpp-coveralls -b ./CMakeFiles/MongooseLibCov.dir/Source -r ../ -i ../Source --coveralls-yaml ../.coveralls.yml -t ${COVERALLS_REPO_TOKEN}