sudo: false

addons:
  apt:
    packages:
    - ggcov
    - valgrind
    - libsuitesparse-dev

os:
  - linux
  - osx

if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
  CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
  mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  export PATH=${DEPS_DIR}/cmake/bin:${PATH}
else
  brew install cmake
fi

language: cpp

compiler:
  - gcc
  - clang

before_script:
  - mkdir _build
  - cd _build
  - cmake ..

script:
  - make VERBOSE=1
  - make test

after_success:
  - ./mongoose_run_all_tests
  - bash <(curl -s https://codecov.io/bash) -t 6bf41c84-78ee-406d-95b8-7f86895b532c
  - valgrind --error-exitcode=42 --leak-check=full ./mongoose_run_all_tests