sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake

before_script:
  - mkdir _build
  - cd _build
  - cmake -DCMAKE_BUILD_TYPE=Coverage ..
  - pip install --user pyyaml cpp-coveralls

script: make

after_success:
  - ./RunTests
  - ./Demo
  - coveralls -t ${COVERALLS_REPO_TOKEN} --coveralls-yaml ../.coveralls.yml -i ../Source