sudo: required
dist: trusty

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake

before_script:
  - mkdir _build
  - cd _build
  - cmake -DCMAKE_BUILD_TYPE=Coverage ..

script: make

after_success:
  - ./RunTests
  - ./Demo
  - coveralls -i ../Source ../Include