sudo: false

addons:
  apt:
    packages:
    - ggcov
    - valgrind
    - libsuitesparse-dev

os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

before_install:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.1-Linux-x86_64.sh"
    mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL}
    ./cmake-3.6.1-Linux-x86_64.sh
  else
    brew install cmake
    brew install valgrind
    brew install suitesparse
  fi

before_script:
  - mkdir _build
  - cd _build
  - cmake ..

script:
  - make VERBOSE=1
  - make test

after_success:
  - ./mongoose_run_all_tests
  - bash <(curl -s https://codecov.io/bash) -t 6bf41c84-78ee-406d-95b8-7f86895b532c
  - valgrind --error-exitcode=42 --leak-check=full ./mongoose_run_all_tests