sudo: required
dist: trusty

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq ggcov
  - sudo apt-get install -qq valgrind

before_script:
  - mkdir _build
  - cd _build
  - cmake ..

script:
  - make VERBOSE=1
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 6bf41c84-78ee-406d-95b8-7f86895b532c
  - valgrind --error-exitcode=42 --leak-check=full ./tests/mongoose_test_memory ../Matrix/Pd.mtx