sudo: required
dist: trusty

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq ggcov

before_script:
  - mkdir _build
  - cd _build
  - cmake -DCMAKE_BUILD_TYPE=Coverage ..
  - pip install --user pyyaml cpp-coveralls

script:
  - make

after_success:
  - ./RunTests
  - ./Demo
  - cpp-coveralls -b ./CMakeFiles/MongooseLibCov.dir/Source --coveralls-yaml ../.coveralls.yml -t ${COVERALLS_REPO_TOKEN}