sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake

before_script:
  - mkdir _build
  - cd _build
  - cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
  - pip install --user pyyaml cpp-coveralls

script:
  - make
  - make coveralls

after_success:
  - ./RunTests
  - ./Demo