os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq ggcov
  - sudo apt-get install -qq valgrind

before_script:
  - mkdir _build
  - cd _build
  - cmake ..

script:
  - make VERBOSE=1
  - make test
  - rm -rf ./*
  - sudo apt-get install -qq libsuitesparse-dev
  - cmake ..
  - make VERBOSE=1
  - make test

after_success:
  - ./mongoose_run_all_tests
  - bash <(curl -s https://codecov.io/bash) -t 6bf41c84-78ee-406d-95b8-7f86895b532c
  - valgrind --error-exitcode=42 --leak-check=full ./mongoose_run_all_tests