codecov:
  branch: edgesep

coverage:
  precision: 2
  round: down
  range: "70...100"

  ignore: 
  - Demo/.*
  - Tests/.*
  - External/.*

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: edgesep
  behavior: default