UserGuide.pdf: UserGuide.tex references.bib Figures/BrotherlyMatching.eps \
    Figures/CommunityMatching.eps Figures/MultilevelOverview.eps
	xelatex UserGuide
	xelatex UserGuide
	bibtex UserGuide
	xelatex UserGuide
	xelatex UserGuide
